name: Java CI with Maven

on: [push, pull_request]

env:
  MAVEN_ARGS: '-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine PR source branch
        id: vars
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF:-develop}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk

      - name: Checkout core
        run: |
          git clone --depth=50 https://github.com/informatici/openhospital-core.git openhospital-core
          cd openhospital-core
          git fetch origin ${{ env.BRANCH_NAME }} || git fetch origin develop
          git checkout ${{ env.BRANCH_NAME }} || git checkout develop
          cd ..
        
      - name: Install core
        run: cd openhospital-core && mvn install -DskipTests=true && cd ..

      - name: Build with Maven
        run: mvn install -DskipTests=true
