# This workflow will update the oh.yaml OpenAPI specification
# For more information see: https://swagger.io/

name: OpenAPI spec generation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout core
        run: git clone --depth=50 --branch=develop https://github.com/informatici/openhospital-core.git openhospital-core
        
      - name: Install core
        run: cd openhospital-core && mvn install -DskipTests=true && cd ..
    
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Generate JWT Token
        id: jwt
        run: echo "::set-output name=token::7DlyD1SHR5pCa4HGgTLWSYm8YQ7oRL1wpPbxyjWyHU44vUrqrooRu3lHVFSXWChesc"
          
      - name: Build with Maven
        run: |
          cp rsc/application.properties.dist rsc/application.properties
          cp rsc/database.properties.dist rsc/database.properties
          cp rsc/log4j.properties.dist rsc/log4j.properties
          cp rsc/settings.properties.dist rsc/settings.properties
          sed -e "s/JWT_TOKEN_SECRET/${{ steps.jwt.outputs.token }}/g" rsc/application.properties.dist > rsc/application.properties
          mvn install -DskipTests=true
        
      - name: Run API
        run: cd target && java -cp "openhospital-api-0.1.0.jar:rsc/:static/" org.springframework.boot.loader.JarLauncher &
        
      - name: Get json
        run: curl -o openapi/oh.json http://localhost:8080/v3/api-docs
        
      - name: Convert to json to yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq -p openapi/oh.json -o yaml openapi/oh.yaml
          
      - name: Update PR
        uses: gr2m/create-or-update-pull-request-action@v1
      
